### PR TITLE
Small typo fix

### PR DESCRIPTION
**Pull request by sjfaz**
*Description of changes:*
Small typo fix.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by switch180** [comment]
What did you change in the themes folder? The commit says you updated the learn theme, but what does that mean?

**Comment by switch180** [comment]
It appears you reverted and removed the AWS theme with this change. I'm reverting this PR.

**Comment by sjfaz** [comment]
> It appears you reverted and removed the AWS theme with this change. I'm reverting this PR.

Apologies I was working from a fork and I updated the fork to the latest but somehow the reference to the theme sub-folder was wrong still.

**Comment by switch180** [comment]
All good! Keep an eye on it next time. Revert is complete in #67. I accepted the inclusion of the word a and reverted the theme.

In the future please be sure to check the master.amazon-dynamodb-labs.com build before you promote the lab to production.

**Pull request merged**
